/**
 * tokenRegistry.ts
 *
 * Built-in token definitions keyed by NetworkKey.
 * These are real tokens on canonical networks (not mock/deployed contracts).
 */

import type { NetworkKey } from "@/src/integration/networks";
import type { Erc20TokenMetadata, NativeTokenMetadata } from "@/src/features/assets/types/token";

export type BuiltinTokenEntry = Erc20TokenMetadata & { networkKey: NetworkKey };
export type BuiltinNativeEntry = NativeTokenMetadata & { networkKey: NetworkKey };

// ─── Base Mainnet Fork ────────────────────────────────────────────────────────

export const BUILTIN_TOKENS_BY_NETWORK: Record<NetworkKey, BuiltinTokenEntry[]> = {
  "anvil-local": [],
  "ethereum-sepolia": [
    {
      chainId: 11155111,
      networkKey: "ethereum-sepolia",
      type: "erc20",
      address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238", // Circle faucet USDC
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tags: ["stablecoin", "sepolia"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 11155111,
      networkKey: "ethereum-sepolia",
      type: "erc20",
      address: "0xfff9976782d46cc05630d1f6ebab18b2324d6b14", // router-canonical Sepolia WETH (SwapRouter02.WETH9 immutable)
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
      tags: ["wrapped-native", "sepolia"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
  ],
  "base-sepolia": [
    {
      chainId: 84532,
      networkKey: "base-sepolia",
      type: "erc20",
      address: "0x036CbD53842c5426634e7929541eC2318f3dCF7e", // Circle Base Sepolia USDC
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tags: ["stablecoin", "base-sepolia"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 84532,
      networkKey: "base-sepolia",
      type: "erc20",
      address: "0x4200000000000000000000000000000000000006", // canonical Base WETH
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
      tags: ["wrapped-native", "base-sepolia"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 84532,
      networkKey: "base-sepolia",
      type: "erc20",
      address: "0xE4aB69C077896252FAFBD49EFD26B5D171A32410", // Chainlink LINK Base Sepolia
      symbol: "LINK",
      name: "ChainLink Token",
      decimals: 18,
      tags: ["oracle", "base-sepolia"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
  ],
  "base-mainnet": [
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x4200000000000000000000000000000000000006",
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
      tags: ["wrapped-native", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22",
      symbol: "cbETH",
      name: "Coinbase Wrapped Staked ETH",
      decimals: 18,
      tags: ["lsd", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb",
      symbol: "DAI",
      name: "Dai Stablecoin",
      decimals: 18,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
      symbol: "AERO",
      name: "Aerodrome Finance",
      decimals: 18,
      tags: ["defi", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452",
      symbol: "wstETH",
      name: "Wrapped Staked Ether",
      decimals: 18,
      tags: ["lsd", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0xB6fe221Fe9EeF5aBa221c348bA20A1Bf5e73624c",
      symbol: "rETH",
      name: "Rocket Pool ETH",
      decimals: 18,
      tags: ["lsd", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2",
      symbol: "USDT",
      name: "Tether USD",
      decimals: 6,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA",
      symbol: "USDbC",
      name: "USD Base Coin",
      decimals: 6,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed",
      symbol: "DEGEN",
      name: "Degen",
      decimals: 18,
      tags: ["meme", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x532f27101965dd16442E59d40670FaF5eBB142E4",
      symbol: "BRETT",
      name: "Brett",
      decimals: 18,
      tags: ["meme", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b",
      symbol: "tBTC",
      name: "Threshold Bitcoin",
      decimals: 18,
      tags: ["btc", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x0578d8A44db98B23BF096A382e016e29a5Ce0ffe",
      symbol: "HIGHER",
      name: "Higher",
      decimals: 18,
      tags: ["meme", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0x60a3E35Cc302bFA44Cb288Bc5a4F316Fdb1adb42",
      symbol: "EURC",
      name: "Euro Coin",
      decimals: 6,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 8453,
      networkKey: "base-mainnet",
      type: "erc20",
      address: "0xCfA3Ef56d303AE4fAabA0592388F19d7C3399FB4",
      symbol: "eUSD",
      name: "Electronic Dollar",
      decimals: 18,
      tags: ["stablecoin", "base"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
  ],
  "arb-mainnet": [
    {
      chainId: 42161,
      networkKey: "arb-mainnet",
      type: "erc20",
      address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tags: ["stablecoin", "arbitrum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 42161,
      networkKey: "arb-mainnet",
      type: "erc20",
      address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1",
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
      tags: ["wrapped-native", "arbitrum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 42161,
      networkKey: "arb-mainnet",
      type: "erc20",
      address: "0x912CE59144191C1204E64559FE8253a0e49E6548",
      symbol: "ARB",
      name: "Arbitrum",
      decimals: 18,
      tags: ["governance", "arbitrum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
  ],
  "eth-mainnet": [
    {
      chainId: 1,
      networkKey: "eth-mainnet",
      type: "erc20",
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tags: ["stablecoin", "ethereum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 1,
      networkKey: "eth-mainnet",
      type: "erc20",
      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
      symbol: "WETH",
      name: "Wrapped Ether",
      decimals: 18,
      tags: ["wrapped-native", "ethereum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 1,
      networkKey: "eth-mainnet",
      type: "erc20",
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      symbol: "USDT",
      name: "Tether USD",
      decimals: 6,
      tags: ["stablecoin", "ethereum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
    {
      chainId: 1,
      networkKey: "eth-mainnet",
      type: "erc20",
      address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
      symbol: "DAI",
      name: "Dai Stablecoin",
      decimals: 18,
      tags: ["stablecoin", "ethereum"],
      isSwapSupported: true,
      isVerified: true,
      source: "builtin",
    },
  ],
  // Populated after this object — derived from base-mainnet (same forked 8453).
  "base-mainnet-fork": [],
};

// base-mainnet-fork mirrors base-mainnet's forked state — same chainId (8453)
// and identical token contracts. Derive the fork's token set from base-mainnet
// so the two lists can never drift apart.
BUILTIN_TOKENS_BY_NETWORK["base-mainnet-fork"] = BUILTIN_TOKENS_BY_NETWORK[
  "base-mainnet"
].map((t) => ({
  ...t,
  networkKey: "base-mainnet-fork",
  tags: [...(t.tags ?? []), "fork"],
}));

const STABLECOIN_ADDRESSES: Set<string> = new Set(
  Object.values(BUILTIN_TOKENS_BY_NETWORK)
    .flat()
    .filter((t) => t.tags?.includes("stablecoin"))
    .map((t) => `${t.chainId}:${t.address.toLowerCase()}`),
);

/** True if (chainId, address) is a known, registry-tagged stablecoin. */
export const isStablecoinAddress = (chainId: number, address: string): boolean =>
  STABLECOIN_ADDRESSES.has(`${chainId}:${address.toLowerCase()}`);
